### ISSUE TITLE
Notabene Error Not Handled

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-reference-wallet-ios#100]
**Bug Description**

An error reported from notabene when submitting an identity object request is not handled. When the error occurs, instead of the usual flow, the request to notabene redirects to the callback URL with an error, such as:
```
concordiumwallettest://identity-issuer/callback/0F463571-D594-43AE-8F8D-789F84BBB5E7#error=%7B%22error%22%3A%7B%22code%22%3A%22INVALID_REQUEST%22%2C%22detail%22%3A%22Invalid%20Identity%20Object%20Request%22%7D%7D
```
In this case, the response should be interpreted as an error, and a message shown to the user. Instead, it is treated as if it were a successful identity issuance and a pending identity/account is created that cannot ever resolve.

(This seems at least in part to be caused by a problem with `parseCallbackUri`. In the case where it does not contain the string `"#code_uri="`, the entire URI is returned.)

**Steps to Reproduce**

Attempt to create an identity while notabene is failing.

**Expected Result**

The identity creation should fail with an appropriate error reported to the user

**Actual Result**

Identity creation appears to succeed without going through the full process, and a pending identity and account are created in the wallet that cannot be resolved.

**Versions**
- Software Version 1.0 (22) Testnet
- OS
- Browser
- Mobile device, if applicable

**Comment by concordium-cl** [comment]
To be discussed: Should the user get the possibility to contact the IDP immediately, so the incident does not necessarily have to go a detour via us?

**Comment by concordium-cl** [comment]
Error message also to be improved in Android: https://github.com/Concordium/concordium-reference-wallet-android/issues/61

**Comment by concordium-cl** [comment]
No immediate test possible.
