### ISSUE TITLE
Missing processing wheel in changing passcode/biometrics flow

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#101]
**Bug Description**
While changing passcode/biometrics and after having entered the new passcode twice, the app gets unresponsive for a long time (up to 20 seconds for wallet with many accounts on iPhone 11) without any waiting indication for the user. It’s very unclear what is going on during that period. We should have a waiting wheel. Preferably the “use full password instead” button should be deactivated, as it is sometimes possible to enter that menu while waiting and that flow will then be interrupted when the password change gets into effect.

**Steps to Reproduce**
- enter the "change passcode"flow
- enter new password
- enter new password
- if possible click on "use full password instead"

**Expected Result**
Waiting wheel indicates processing time. Button "use full password instead" cannot be pressed.

**Actual Result**
App is unresponsive. It might be possible to enter the "use full password instead" flow.

**Versions**
- 1.0.22
- iOS 14.7
- iPhone 11

**Comment by jens-concordium** [comment]
This seems to work on iOS 15, but probably good to check on iOS 14 as well. @concordium-cl

**Comment by concordium-cl** [comment]
Checked on iOS 14.7.1. 

Fixed in 1.0.23
