### ISSUE TITLE
Updating from an old version to 1.0(22) causes a crash

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#103]
**Bug Description**
If you have an old version of the mobile wallet installed, e.g. 1.0(6) and then update 1.0(22), the app will crash upon reopening it. On iOS 14.7 it will give a pop-up saying that the app has crashed and on iOS 15 the app will show for a split second, before just disappearing without any pop-ups.

This might be related to the iOS 15 SDK upgrade.

**Steps to Reproduce**
- Install an old version of the app, e.g. 1.0(6), set it up and maybe populate it with a bit of data.
- Update to 1.0(22) without uninstalling the old version first. 
- Try to open the app, and notice how it crashes. 

**Expected Result**
- The app opens after update without problems.

**Actual Result**
- The app cannot be opened after an update to 1.0(22), because it crashes immediately. 

**Versions**
- Software Version: 1.0(22)
- OS: iOS 14.7 and 15

**Comment by concordium-cl** [comment]
Checked on iOS 14.7.1.

Fixed in 1.0.23.
