### ISSUE TITLE
Line under account name input field and Continue button can disappear

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#104]
**Bug Description**
When making a new account and entering a name for it, the line under the input field will disappear below the keyboard, if you go forward and then back again. It might be good to put both the button and line above the keyboard. This is likely related to the removed dependency during the update to the iOS 15 SDK. 

![image](https://user-images.githubusercontent.com/76045015/141476756-3ccf40dd-51f6-4ff4-be87-dd3db5c9a548.png)

**Steps to Reproduce**
- Start making a new account
- Enter a name for the account
- Go forward one page, and then go back again. 
- Notice how the line under the input field has appeared, and the Continue button is also nowhere to be seen.

**Expected Result**
- Both the line and the button stays above the keyboard.

**Actual Result**
- The line and the button seems to be hidden behind the keyboard.

**Versions**
- Software Version: 1.0(22)
- OS: iOS 14.7 and 15

**Comment by jens-concordium** [comment]
@kristiyandobrev, it should be possible to hide the keyboard by click somewhere outside the input field now, right? I can't get it to work in all places, on iOS 15.0. The input field kind of slides down behind the keyboard as if the keyboard was about to disappear, but the keyboard stays up. The same thing happens, when I press the suggestions I get. It seems to only be a problem for account and identity name inout fields for some reason.

https://user-images.githubusercontent.com/76045015/142431527-b71d28ad-cb08-407a-bc38-3f893f330028.MOV

**Comment by concordium-cl** [comment]
Verified in v1.0.26, iOS 14.7.1, iPhone11.
