### ISSUE TITLE
Letting the app time out on a passcode page will cause it to hang

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#105]
**Bug Description**
On pages where the user has to input the passcode, letting the app time out will cause it to hang forever. This is presumably caused by two lock screens on top of each other.

Different solution options:

1. Let the user finish what it’s doing without dismissing it’s flow in favour of the “passcode view”
2. Dismiss what the user is doing and bring the passcode view.
3. As a general rule of thumb, passcode view should not kick in if there is another passcode view before it.

**Steps to Reproduce**
- Set up the app to use passcode.
- Start making a new account, and continue untill passcode is needed
- Don't continue and let the app time out.
- The app will start hanging.

**Expected Result**
Depends on the chosen solution.

**Actual Result**
- App hangs forever

**Versions**
- Software Version: Probably all of them
- OS: iOS

**Comment by concordium-cl** [comment]
Will be followed in jira https://concordium.atlassian.net/browse/CBW-635
