### ISSUE TITLE
Rename GTU or G to CCD or C, respectively

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#114]
**Description**

**Steps to Reproduce**

**Expected Result**

**Actual Result**

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by jens-concordium** [comment]
@concordium-cl, this looks good to me on iOS 15 in v1.0(25).

**Comment by concordium-cl** [comment]
Verified also on iOS 14.7.1, iPhone11, v1.0.25.
