### ISSUE TITLE
Let user remove non-existing accounts and incorrectly verified identities

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#120]
**Description**

Some users have experienced that their initial accounts don't exist in the chain, even though the seem perfectly fine and verified in the iOS wallet. This is due to incorrectly verified identities, that shouldn't in fact have been verified. 

This problem was solved in a later version of the wallet, but the initial accounts and identities remain and cannot be removed because the wallet thinks they are working as intended. 

We should add an option to let the user make a check of accounts and identities, to see if they in fact exist. If the check reveals that the account does not exist on the chain, we should let the user remove the account and related identity. _If the account does exists, the option to remove it should not be there._ 

So far this has only been a problem on iOS, but we should consider doing this on Android as well, just in case.

**Comment by concordium-cl** [comment]
Needs thorough consideration, which cases to handle.

**Comment by concordium-cl** [comment]
Added after slack discussion:

**Comment by concordium-cl** [comment]
Moved to backlog, as we have low confidence that it can be resolved atm.

**Comment by concordium-cl** [comment]
Identities fixed. Other is obsolete.
