### ISSUE TITLE
Transaction list is prone to UI errors

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#125]
**Bug Description**

The list of transactions has started to become a bit prone to small UI errors. It would probably be good to get it cleaned up a bit. 

It's entirely certain what causes these smalls errors to happen, but once in a while they pop-up. See the attached screenshot for examples, e.g.:

- A lot of white space to the right of amounts
- Extra whitespace above dates, like "Yesterday" and "Today" in the screenshot.
- The grey line below the slightly blue area of the date field doesn't go all the way to the left.

![IMG_3C69E36EE6BA-1](https://user-images.githubusercontent.com/76045015/144048164-4f9e9963-a413-4b8e-8f40-1d89a505e3f2.jpeg)

**Versions**
- Software Version: 1.0(26), and probably earlier versions as well.
- OS: iOS

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: Testnet 2.0
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE
