### ISSUE TITLE
Testnet wallet crashes when iPhone is locked

### ISSUE THREAD

**Issue by BeanBagBob** [Concordium/concordium-reference-wallet-ios#133]
**Bug Description**
After unlocking my iPhone I am often greeted with a popup telling that the "Concordium Testnet Wallet" crashed.
After tapping "No thanks" it reappears multiple times. I think this happens even if the wallet is not open in the background. See attached screenshot. The wallet works without problems though.

**Steps to Reproduce**
Install Testnet wallet. Lock iPhone. Wait. Unlock iPhone.

**Expected Result**
No popup.

**Actual Result**
Popup appears.

**Versions**
- Software Version
-   1.1.27, but previous versions also had the problem
- OS
-   iOS 15.1
- Browser
- Mobile device, if applicable
-   iPhone 8

![IMG_3273](https://user-images.githubusercontent.com/73488895/146548700-e1c9b4ea-23f9-4858-8774-e1431dfe02b0.jpg)

**Comment by concordium-cl** [comment]
I have the same issue on iPhone11, iOS 15.1, CCD 1.1.27

**Comment by jens-concordium** [comment]
I have had this happen on iOS 15.0 and iOS 15.1 for a while as well. It has been gone for me a few days now on iOS 15.2, but @dg-concordium has had it happen on 15.2 as well, as far as I know.

**Comment by jens-concordium** [comment]
This has been happening consistently again over the last week's time on iOS 15.2 for me.

**Comment by ZB-concordium** [comment]
Verified.
Wallet version: 3.0.0 (44)
iOS: 15.5
Device: iPhone SE

**Comment by concordium-cl** [comment]
Needs to be verified on testnet app. Back to Ready for Test.

**Comment by mh-concordium** [comment]
I was not able to reproduce the issue. Tested also with 'autolocking' screen.

Wallet version: Testnet app 3.0.0 (50)
iOS: 15.5
Device: iPhone SE
