### ISSUE TITLE
Missing backup banner

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#139]
**Description**
There should be an additional top banner in the wallet that stays if user has not backed up wallet after new accounts have been created.

The banner should look something like the one shown below in the screenshot. 

![image](https://user-images.githubusercontent.com/76045015/148404453-d283c334-4c90-4b8c-82ce-724ac70b4f28.png)

**Steps to Reproduce**

**Expected Result**

**Actual Result**

**Versions**
- 1.1.27
- mainnet

**Comment by eb-concordium** [comment]
In the Testnet app version 1.2.29 on iPhone SE (from 2016) running iOS 13.5.1, it seems that the banner does only disappears when I make a backup via either one of the first two pop-ups (after creating a new account) or the banner itself. If I make a backup via "More -> Export", the banner does not disappear.

**Comment by kristiyandobrev** [comment]
> In the Testnet app version 1.2.29 on iPhone SE (from 2016) running iOS 13.5.1, it seems that the banner does only disappears when I make a backup via either one of the first two pop-ups (after creating a new account) or the banner itself. If I make a backup via "More -> Export", the banner does not disappear.

Hey 👋🏻 Thanks for the good catch. Found and fix the bug already :)

**Comment by concordium-cl** [comment]
Verified on testnet CCD app v1.2.30.
