### ISSUE TITLE
Modify intro flow

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#140]
**Description**
Modify text on intro page "create an initial account"or "import existing accounts".

The new text is shown in the screenshot below, and the only change is to the middle sentence, which is now: 

"In case this is not your first time around, you must import existing accounts to get access to them."

All the text should also be changed to black.

![image](https://user-images.githubusercontent.com/76045015/148404721-a3b2d259-1a32-4c1b-9c1f-74fb518185de.png)

**Steps to Reproduce**

**Expected Result**

**Actual Result**

**Versions**
- 1.0.22
- mainnet

**Comment by concordium-cl** [comment]
Verified in testnet CCD app v1.2.30.
