### ISSUE TITLE
Graceful handling after restoring

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#141]
**Task description**
A user creates a backup with the old app and then restores after the new app is released. The app must handle this situation gracefully.

<placeholder>

**Versions**
- 1.1.27
- Mainnet

**Comment by eb-concordium** [comment]
During some tests, after seeing the pop-up with the options “Remind me later”, “Keep as read-only” and “Import keys from backup”, and after choosing "Remind me later", the app crashed. Not immediately, but after a minute or so, while watching the account list containing one or more read-only accounts. I'm not sure if it's related to the pop-up at all, but nonetheless it happened more than once, after pressing "Remind me later" and looking at the account list for a bit.

App Version: 1.2(29),
iPhone SE (from 2016) running iOS 13.5.1.

**Comment by concordium-cl** [comment]
Jens couldn't reproduced. Might be indirectly fixed by fix for https://github.com/Concordium/concordium-reference-wallet-ios/issues/130.
