### ISSUE TITLE
Backup dlg immediately after upgrading wallet

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#147]
**Description**
After upgrading to a new version, the user should be prompted to backup. Most current users will be in that situation, without necessarily creating an account immediately after upgrading.

Text and buttons:

```
Welcome back!

Did you make a backup of your identities and accounts recently?

If you didn’t, now is a good time to do so! Concordium strongly recommends having a backup of all your identities and accounts. 
```
Left button: Not now
Right button: Make backup

![image](https://user-images.githubusercontent.com/76045015/149350574-51b62754-cdc9-414d-b85d-634db905ddb5.png)

 
**Steps to Reproduce**
- in old version, create id and account
- upgrade to new version

**Expected Result**
There should be an info box asking the user to make a backup, if he didn't do so in the old version, with two buttons "Dismiss" and "Okay" (leading to export). "Dismiss" should lead to the existing warning "are you sure?".

**Actual Result**
Warning dilaogs and "nagging box" first appear after new account creation.

**Versions**
- CCD testnet ?

**Comment by concordium-cl** [comment]
Discovered when testing Android.

**Comment by kristiyandobrev** [comment]
@concordium-cl 

Should that the case also for future updates ?

**Comment by concordium-cl** [comment]
@jens-concordium, what do you think?

**Comment by jens-concordium** [comment]
I guess it should. There could be cases where a user updates from an older version and directly to a later version than this one, in the future. @jensvesti, how is this handled in Android?

**Comment by concordium-cl** [comment]
To be tested

1.0.5 --> newest version: prompt shown
1.1.27 --> newest version: prompt shown

new install of newest version: no prompt

**Comment by concordium-cl** [comment]
1.1.27 --> 1.2.31: prompt shown ✅ 
new install of 1.2.31: no prompt ✅ 
1.0.7 --> 1.2.31: prompt shown ✅ 

Note: Dlg text here is outdated, see https://github.com/Concordium/concordium-reference-wallet-ios/issues/150.
