### ISSUE TITLE
Change text in backup reminders

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#150]
**Task description**

The text in the backup reminders has to be changed a little bit. It affects the reminder on new account and the "Welcome back" reminder shown on update, the warning of the other reminders are dismissed and the banner shown, when accounts have not been backed up.  The new texts can be seen in the screenshots below, and can be copied here from within the  Figma link below. 

If possible, we'd also like the exported backup file renamed to "concordium-backup.concordiumwallet". 

https://www.figma.com/file/pUlYPsHRU0Hvm0NoGIvxrv/Mobile-Wallet?node-id=2860%3A13745

On new account:
![image](https://user-images.githubusercontent.com/76045015/150291701-4fcbad96-5c05-43aa-bf0f-35d3a7ce58e9.png)

On updating the wallet app:
![image](https://user-images.githubusercontent.com/76045015/150291750-285de6b0-d0f6-4034-8984-4f20eb02321f.png)

**Comment by concordium-cl** [comment]
Step 3 in "On updating the wallet app" not present. Nagging box first shows up after new account creation. Tested update from released 1.1.27 to newest 1.2.31.

**Comment by concordium-cl** [comment]
Step 1 in "On new account" shows wrong text (old version not as given above). Tested on newest 1.2.31.
![IMG_5708](https://user-images.githubusercontent.com/69570978/151339177-775160b1-7ce1-45a9-a99a-605c4698fe6f.PNG)

**Comment by concordium-cl** [comment]
@kristiyandobrev, please note there are two issues/comments in this context.

**Comment by concordium-cl** [comment]
Verified in CCD app 1.2.33, iPhone11, iOS 15.1.
