### ISSUE TITLE
Signing of transactions generated by a DAPP flow

### ISSUE THREAD

**Issue by kristiyandobrev** [Concordium/concordium-reference-wallet-ios#154]
**Task description**

The Wallet app should be able to sign transactions generated by a DAPP. The secure connection between the Wallet and the DAPP could be established via [Wallet Connect](https://walletconnect.com). 

The following scenarios must be handled: 

* Opening/Closing a session with the DAPP
* Approving transactions. 

[Figma document containing the flow](https://www.figma.com/file/pUlYPsHRU0Hvm0NoGIvxrv/Mobile-Wallet?node-id=2390%3A9234)

**Comment by concordium-cl** [comment]
Irrelevant by now.
