### ISSUE TITLE
Update simple and shielded transaction flows

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#158]
**Task description**

The transaction flows for the simple and shielded transaction should be updated a bit. 

The first need-to-have update is a new option to just paste a recipient address, while the user should also be able to scan a QR code or look up addresses in the address book. 

The second need-to-have update is an update to the available funds area shown at the top. As the shielded balance will be hidden as default, the shielded balance shouldn't be mentioned at the top of the transaction page. Instead it should show the public balance total, and the amount at disposal. 

The two need-to-have updates are highlighted in the screenshot below. The full flow can be seen in "Flow 1" and "Flow 4" here: https://www.figma.com/file/pUlYPsHRU0Hvm0NoGIvxrv/Mobile-Wallet?node-id=2881%3A13697

You will see that the flows contain other changes compared to what we have now, but these are nice-to-have and will be described in another issue. 

![image](https://user-images.githubusercontent.com/76045015/151314912-44d347ed-aef1-4192-bef7-2f6cd805c90b.png)

**Comment by mh-concordium** [comment]
Verified. Need to be retested after bug fixing. 

**Versions**
- Software Version: Testnet 2.0.35
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE

**Comment by mh-concordium** [comment]
Verified.
Tested: Simple transfer, shielded transfer, scheduled transfer (sent from DW, received on MW). Initial accounts, restored accounts from backup.

**Versions**
- Software Version: Testnet 2.0.0 (36)
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE
