### ISSUE TITLE
Hide the shielded balance

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#160]
**Task description**

Most users have no use for the shielded balance, for which reason the shielded balance is too prominent in the UI, and causes more confusion than benefit. For this reason the shielded balance has to be hidden behind an option that needs to be enabled, before it's shown in the wallet. Then users who need it will be able to actively go and find it themselves, and all the rest who don't need it will not be bothered by it. 

This issue has three flows in Figma, i.e. Flow 3, Flow 5 and Flow 6. The main changes are shown in Flow 3, and then 5 and 6 has some smaller changes to finish the complete update to the wallet. All three flows contain need-to-have changes, but you will also be able to find nice-to-have changes, which will be put into separate issues. 

For information, the nice-to-haves are:
- [New styling on the "Send", "Shield", "Unshield", "Send (shielded) and "Receive" buttons.](https://github.com/Concordium/concordium-reference-wallet-ios/issues/170)
- [New flat styling of the transaction log.](https://github.com/Concordium/concordium-reference-wallet-ios/issues/171)

There are some need-to-haves from other issues, those are:
- [The redesigned account cards](https://github.com/Concordium/concordium-reference-wallet-ios/issues/86)
- [The updated navigation bar](https://github.com/Concordium/concordium-reference-wallet-ios/issues/161)
- [The updated "totals areas"](https://github.com/Concordium/concordium-reference-wallet-ios/issues/169)

Notes:
- You will be able to see a "Delegation" button in the dropdown menu. This is future work, so you can disregard that for now. 
- There will be a challenge in keeping track of new shielded transaction in the background.

**Comment by mh-concordium** [comment]
Verified. However, the case where burger menu is available on Shielded balance page should and will be retested with https://github.com/Concordium/concordium-reference-wallet-ios/issues/190.
