### ISSUE TITLE
Hide the identities page + redesign of navigation bar.

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#161]
**Task description**

After the user has their first verified identity, there is not much reason to keep it as such a prominent part of the UI. Some users even thought the identity was their account, so it was decided to move the identities page from the navigation bar to the more menu, as way to make the identities less prominent in the UI.

As the identities will no longer be part of the navigation bar, there is instead room for a direct path to make a backup. The new navigation bar and More page can be seen below in the screenshot, or in "Flow 8" in Figma. 

![image](https://user-images.githubusercontent.com/76045015/152167942-85a6ecd3-b1f2-437b-bd59-544831baaa50.png)

Notes:
- Export is also going to be renamed "Make backup" and Import is going to be renamed to "Restore backup". This has the implication that the text and title on the "How to import on iOS" page has to be updated. This is also shown in Flow 8 in Figma, and in the second screenshot below.

![image](https://user-images.githubusercontent.com/76045015/152168578-1c7bfc61-4eca-41f0-ada9-2c2515b85313.png)

**Comment by mh-concordium** [comment]
Verified. Only one minor finding that will be documented as change request. 
Finding is related to "Validate ID" while there is a failed identity. We don't show that identity has failed but instead just say everything is valid.

**Versions**
- Software Version: Testnet 2.0
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE
