### ISSUE TITLE
Nagging box and "new account ready" dlg not triggered on identity page

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#162]
**Bug Description**
For initial accounts, nagging box and "new account ready" dlg is NOT triggered, when user waits on identity page for id issuance to complete. Also when then navigating back and forth, box and dlg do not show. When waiting on accounts page, box and dlg show, also for initial accounts.

**Steps to Reproduce**
- create a new id
- after completing the flow, press button "continue"
- stay on page "Identities"
--> Wait until id is finalized. Observe that there is no nagging box or backup dlg triggered.
- navigate through app and reload
--> Observe that there is no nagging box or backup dlg triggered.

**Expected Result**
Nagging box and "new account ready" dlg is triggered, not matter which page is opened in app.

**Actual Result**
For initial accounts, nagging box and "new account ready" dlg is NOT triggered, when user waits on identity page for id issuance to complete. Also when then navigating back and forth, box and dlg do not show.

**Versions**
- 1.2.31
- iOS 15.1
- iPhone 11

**Comment by concordium-cl** [comment]
Double-checked test case on Android, where it works as expected.

**Comment by ruxandra-constantinescu** [comment]
@concordium-cl on iOS we do not show any account related dialogs on the identity screen. Would it suffice to have the dialog displayed (with teh box as well) in the accounts screen?

**Comment by concordium-cl** [comment]
@ruxandra-constantinescu: Yes, it should pop up when you return to the account page.

**Comment by concordium-cl** [comment]
Verified in CCD app 1.2.33, iPhone11, iOS 15.1.
