### ISSUE TITLE
Create identity button on empty accounts page goes under navigation bar

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#168]
**Bug Description**
The "Create identity" button that appears on the accounts screen when there are no accounts in the wallet, sits behind the navigation bar. See screenshot below.

![image](https://user-images.githubusercontent.com/76045015/151932043-c9537a51-7dbd-4223-8d7a-bc3dd51c39ac.png)

**Steps to Reproduce**
- Install new wallet.
- Force the first identity to fail, so the initial account gets removed from the app.
- Notice how the button is behind the navigation bar.

**Expected Result**
- Button is above the navigation bar.

**Actual Result**
- Button is behind the navigation bar.

**Versions**
- Software Version: 1.2(33)
- OS: iOS
- Mobile device: iPhone XS

**Comment by mh-concordium** [comment]
Tested on testnet 2.0.35. This is still an issue.

iOS 15:
![IMG_61958EB0EDAF-1](https://user-images.githubusercontent.com/98821384/155970515-bd0a99e6-6fd8-450c-ae20-71e5498652b2.jpeg)

iOS 14.8. - there is no "Create identity button at all"
![Slack Image (2022-02-28_11-43-33-115)](https://user-images.githubusercontent.com/98821384/155970692-a78b13ce-b8ad-4d46-a3dd-ff0d8c4832e6.jpg)

**Comment by ruxandra-constantinescu** [comment]
Fixed in next build

**Comment by concordium-cl** [comment]
Verified in 2.0.0 (36).

Button is not above navigation bar anymore. However, it is too low on the page, which is added to [issue](https://github.com/Concordium/concordium-reference-wallet-ios/issues/212) collecting other occurrences of same problem.
