### ISSUE TITLE
Hour not visible in Release Schedule

### ISSUE THREAD

**Issue by eb-concordium** [Concordium/concordium-reference-wallet-ios#17]
**Description**
Only the date is visible when opening Release Schedule on iOS

**Steps to Reproduce**
1. Make a scheduled transfer to some account, say A. 
2. Go to the account balance of A.
3. Press the menu button in the top right corner and select Release Schedule.

**Expected Result**
That the hour and minutes of each release are visible.

**Actual Result**
Only day, month and year are fully visible. See the below screenshot.
<img src="https://user-images.githubusercontent.com/77331975/117827375-3549a700-b271-11eb-9831-b1eb28aabc8a.png" width="300"/>

**Versions**
- Software Version: 0.1.69
- OS: iOS 13.5.1 
- Phone: iPhone SE

**Comment by concordium-cl** [comment]
iPhone SE not longer supported.
