### ISSUE TITLE
New flat styling of ID cards

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#172]
**Task description**

In Flow 7 in Figma a new flat styling for the identity cards can be seen. This is nice-to-have with low priority. Besides being flat, the ID cards now also have coloured edges matching their status a bit. 

**Important!** Please coordinate between between iOS and Android development, so these nice-to-have changes are only done, if there is time to do them on both platforms. 

The new styling can also be seen in the screenshots below:
![image](https://user-images.githubusercontent.com/76045015/152173066-0490b1b8-eae0-4740-b063-79098656c7f1.png)
![image](https://user-images.githubusercontent.com/76045015/152173101-d94085d4-0230-47bf-9526-360a612a69e0.png)
![image](https://user-images.githubusercontent.com/76045015/152173135-f18c50fd-11e8-46ea-a9b8-342990e04212.png)

**Comment by mh-concordium** [comment]
Verified in Testnet MW 2.0.35.
iPhone SE.
iOS 14.8.
