### ISSUE TITLE
Reintroduce the "lock" indicating still encrypted amounts on the shielded balance

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#174]
**Task description**

During the rework of the mobile wallet UI, the shielded balance was hidden behind an option and the Accounts page was redesigned with a reworked totals area and new account cards. 

Because of time constraints, it was decided to now show the "lock" icon on accounts that contained some amount of encrypted CCDs on the shielded balance, as this would require some extra work on the logic handling this. 

To reintroduce the lock icon, the following would have to be done:

- Get account balance at import and decrypt selfAmount and incomingAmounts (still at import.. while we still have access to the keys)
- Show "+ lock" for account total in the overview if totalShieldAmount (selfAmount + incomingAmounts) is not zero or if it is encrypted
- Show "+ lock" for general total accounts balance if there is an account for which the totalShieldedAmount !=0 or is encrypted

**Comment by concordium-cl** [comment]
Will move to jira.
