### ISSUE TITLE
Sort address book entries alphabetically

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#19]
**Description**
The desktop wallet and the Android version of the mobile wallet sorts address book entries alphabetically. It would be nice if the iOS app does the same.

**Steps to Reproduce**
Watch entries in the address book on iOS and notice that they are sorted in the order they are added.

**Expected Result**
They are soreted 0-9 and then A-Z.

**Actual Result**
They are sorted in the order they are added.

**Versions**
- Software Version: Testnet 0.1.68
- OS: iOS 14.5
- Browser: Not applicable
- Mobile device: iPhone XS

**Comment by concordium-cl** [comment]
Ignore case when sorting.

**Comment by jens-concordium** [comment]
Findings from testing:
It seems to work as intended.
