### ISSUE TITLE
Delegation: The status page

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#196]
**Task description**
As a part of the delegation implementation in the Concordium Mobile Wallet, we are going to need a status page, that will allow the user to inspect their current delegation. 

As it can be seen in Flow 1 in Figma, the delegation status page can be entered via the burger menu of the specific account pages. There are two different scenarios in this context:
- Scenario 1, where the account is not already delegating. In this case the burger menu will also show a baking option, and it the user presses the Delegation option, they will be met with a carousel explaining delegation, before they enter the status page.  
- Scenario 2, where the account already has an active delegation. In this case only the delegation button is shown, and the carousel is not shown at this point. Additionally, in scenario 2 it can be seen on the specific account screen, how much is currently delegated with either an open pool, or with the L-pool. 

<br/>
<br/>

As it can be seen in Flow 6 in Figma, the status page can have different states, depending on the current delegation status. 

1. A state with no current delegation (Can also be seen in context in Flow 1)
2. A state awaiting a delegation transaction to finalize (Can also be seen in context in Delegation status scenario 1)
3. A state with a "regular" status, with no pending changes (Can also be seen in context in Delegation status scenario 1)
4. A state with with a pending decrease in delegation amount, meaning the amount cannot be touched for the cooldown period, and the delegation cannot be stopped. (Can also be seen in context in Delegation status scenario 2)
5. A state with a pending stop of the delegation, meaning the amount cannot be touched for the cooldown period, and the delegation cannot be stopped again. (Can also be seen in context in Delegation status scenario 4)
6. A state where the baker pool is in a "shut down" cool down period, so the user can see a message about this.
7. A state where a delegation transaction failed, hence the user is shown an error message. (Can also be seen in context in Delegation status scenario 1)

<br/>
<br/>

**The complete list of what information can be found in the delegation status:**
- Delegating account (Name + account address)
- Delegation amount (Amount of CCD delegated)
- Target baker pool (the baker ID of the pool)
- "Rewards will be" (Added to stake | Added to delegation amount)

If there are pending changes, the message "The following changes will take effect in approximately XX days" will be shown at the bottom, follow by either:

- New delegation amount (the new delegation amount)

or

- "The delegation will be stopped, and the delegation amount will be unlocked on the public balance of the account. "

And lastly, if the target bool is in cool down to close down, the following message will be displayed:

- "This pool has been deregistered, and will stop baking after it’s cool down has ended in <amount of time>"

**Comment by mh-concordium** [comment]
Verified.
**Versions**
- Software Version: 3.0.0 (39)
- OS:14.8.1
- Browser
- Mobile device: iPhone SE
