### ISSUE TITLE
Delegation: Updating a current delegation

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#198]
**Task description**
If an account already has a registered delegation, it is possible to make updates to it. A transaction to update a current delegation can be started from the [delegation status page](https://github.com/Concordium/concordium-reference-wallet-ios/issues/196). 

When making an update to the delegation, the parameters of the ConfigureDelegation transaction are optional, so the user can pick whichever parameters to update. If they end up in a situation where they are about to submit no changes, the user will be notified so they don't waste a transaction fee. 

Examples of such a transaction flow can be seen in Flow 3 and 7 in Figma. 

Flow 3 is an example of decreasing the delegation amount, with no other changes to the delegation. Pressing the "Update current delegation" button in **Delegation status scenario 1**, will start the flow of updating the delegation. At first the user will be met by a carousel explaining delegation concepts, and the rest of the pages [equals what we have in the register delegation transaction.](https://github.com/Concordium/concordium-reference-wallet-ios/issues/197).

Flow 7 in Figma shows three special scenarios, that will have an effect on the update delegation transaction flow. 

- Scenario 1 is when the user is setting the delegation amount to 0, which means they are effectively stopping the delegation. This will yield a notification, letting the user know about this.
- Scenario 2 is when the user has made no changes to the delegation, yielding a notification letting them know about this.
- Scenario 3 shows the situation, where the user decides to delegate to the L-pool, hence no pool information / limits will be shown on the amounts page.

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: 3.0.0 (39)
- OS:14.8.1
- Browser
- Mobile device: iPhone SE
