### ISSUE TITLE
Unshielded amount shown as negative until committed

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-reference-wallet-ios#2]
**Bug Description**
Unshielded amounts are shown as negative until committed/finalized.

<img src="https://user-images.githubusercontent.com/5469652/116415969-383ca480-a83a-11eb-84cf-b64bf453e672.jpg" width="400" /><img src="https://user-images.githubusercontent.com/5469652/116415974-3a066800-a83a-11eb-8585-021ad3e7edf9.PNG" width="400" />

**Steps to Reproduce**
1. Unshield an amount, fx `10`, on account `A`.
2. Quickly go to public balance for account `A`.
3. Notice that it says `-G10,00~ -G1,6415 Fee` despite it being _added_ to the account.
4. Wait until the transaction has been committed/finalized. See that it correctly shows `G10,00 -G1,6415 Fee`

**Expected Result**
Unshielded amount should be shown as positive throughout the process.

**Actual Result**
Unshielded amount is shown as negative until transaction is committed/finalized.

As a side-note from the comment below, and as also seen in the screenshot:
There should be a space between the - and the fee amount, i.e., {amount} - {fee} instead of {amount} -{fee}.

The tilde (~) is supposed to indicate that it is an approximate fee, and right now it's position is misleading. Instead it should be {amount} - ~{fee}.

**Versions**
- Software Version: 0.1.69
- OS: iOS 14.4.2
- Browser: Brave
- Mobile device: iPhone 11 Pro

**Comment by dkrmjolner** [comment]
Ive only fixed the part with "-" and "~". 
By agreement with Jens the negative amount is not fixed, because if the complexity of this minor bug.
