### ISSUE TITLE
Baking: Update pool settings

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#204]
**Task description**

Similarly to the [Update baker stake flow](https://github.com/Concordium/concordium-reference-wallet-ios/issues/203), the Update pool settings flow have common elements with the [Register baker flow](https://github.com/Concordium/concordium-reference-wallet-ios/issues/202).

Instead of updating baker stake and restaking status, the Update pool settings flow will be able to update:

- Pool status (Open | Close for new delegators | Close for delegation)
- MetadataURL (String | Empty string)

The flow can be accessed from the [baker status page](https://github.com/Concordium/concordium-reference-wallet-ios/issues/201). This flow will also start with a skippable carousel that explains baking concepts.

In the box called **Update pool settings** in Figma, two scenarios can be found.

Scenario 1:
Scenario 1 shows all the steps of Update pool settings flow. 
- The first thing the user must consider is the pool status (Open | Close for new delegators | Close for delegation). They can leave it as it is, if they don't want to make any changes. There is a special scenario, where the current pool is closed, in which the options will only be (Open | Close for delegation), as it makes no sense to have the "Close for new delegators", when there are no current delegators. 
- On the next page, the user must consider what they want to do with the metadata URL. They can leave it as it is, change it, or remove it all together. In case they leave it empty, we just submit an empty string. 
- The presubmission overview of the transaction ticket will show the affected parameters. If the metadataURL is empty, we just state "Empty". 
- The same goes for the overview after the submission, just with the transaction hash now shown.
- Lastly, before the user is taken to the baker status page, a notification is shown, letting the user know that the change will take effect from the next pay day.

Scenario 2:
Scenario 2 displays what will happen if the user ends up making no changes in the transaction.

**Comment by EmilLa1** [comment]
3.0.0 (48)
