### ISSUE TITLE
Rename menu entry to "Restore from backup"

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#208]
**Description**
Menu entry should be renamed. It is only text but describes two different scenarios, with the current one "restore backup" being what users probably look for but what we cannot provide. As this is a bit of a delicate situation, I think our communication must be spotless.

The text on the page itself is correct. Only the menu item must be changed.

![IMG_5930](https://user-images.githubusercontent.com/69570978/156537211-35c48852-3217-4f36-97d2-f39b710bf571.jpg)

Screenshot is from iOS but Android looks similar. Figma screen is wrong as well.

**Steps to Reproduce**
Go to "More" menu

**Expected Result**
Restore from backup

**Actual Result**
Restore backup

**Versions**
- CCD app iOS 2.0.35, Android 2.0.70

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: Testnet 2.0.0 (36)
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE
