### ISSUE TITLE
Minor UI bugs

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#212]
**Bug Description**
Collection of minor UI bugs.

**Steps to Reproduce**
1. Button on page "How to restore from backup on iOS"  (Image Button1).
2. Button on page "Reveal Identity data"  (Image Button2).
3. Border for backup warning is not yellow as proposed (Image Yellow Border).
4. Button on page "Accounts" after very first identity failed (Image Button4).

**Expected Result**
For 1 and 2 and 4: buttons are usually visually separated from the bottom of the view.
For 3 border for warning should be yellow.

**Actual Result**
For 1 and 2 and 4: buttons are on the bottom of the view.
For 3 border for warning is blue instead of yellow.

_Images:_

Button1
<img width="247" alt="Button1" src="https://user-images.githubusercontent.com/98821384/156727018-d8d97b53-6dd7-47c2-9370-0a6d277462fc.png">

Button2
<img width="250" alt="Button2" src="https://user-images.githubusercontent.com/98821384/156727040-f5459b28-4173-489e-9175-05d4f398e0c1.png">

Yellow border
<img width="377" alt="Yellow border" src="https://user-images.githubusercontent.com/98821384/156727113-277da37c-a42e-4482-b36d-5fbc4dc3612b.png">

Button4
![IMG_5977](https://user-images.githubusercontent.com/69570978/157615135-025c8151-d31e-46e0-b33e-5ba6565f07f7.PNG)

**Versions**
- Software Version: Testnet 2.0.35/2.0.36
- OS: iOS 14.8/15.1
- Browser: N/A
- Mobile device: iPhone SE/11

**Comment by EmilLa1** [comment]
3.0.0 (48)

1. Button has been moved up.
2. Button has been moved up.
3. Border is yellow.
4. Unable to get to this flow on stagenet.

**Comment by mh-concordium** [comment]
Last check (number 4.) verified on 3.0.0 (52). Border is yellow now as proposed.
