### ISSUE TITLE
Rethink balances naming

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#214]
**Task description**

How can we make naming of balances less confusing?
Naming should be consistent across the views and aligned across iOS and Android.

**Sub-tasks**
- Rethink naming of the account balances, make a draft and review it with all necessary stakeholders
- Implement on iOS MW
- Align iOS with Android

Attached image is idea/draft of balances strings
<img width="2514" alt="ChangeRequest" src="https://user-images.githubusercontent.com/98821384/157005850-41931fd1-f68e-472f-94ab-ef0ab1277411.png">

*Add label for component and priority.*

**Comment by concordium-cl** [comment]
Will move to jira.
