### ISSUE TITLE
Delegation/Baking: Fill in carousel content

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#216]
**Task description**

This is a placeholder task for now. Will be filled out when then content for the carousels is ready.

**Comment by EmilLa1** [comment]
@jens-concordium 

What is this about? Is it about the guide(s)?

**Comment by jens-concordium** [comment]
@EmilLa1, yep exactly. I think they might also be covered in other issues.

**Comment by EmilLa1** [comment]
3.0.0 (48)
