### ISSUE TITLE
Scan QR to get an address hangs

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#219]
**Bug Description**
Using camera to scan QR code for the address keeps hanging once address was scanned. 
This happens for both transfers.

**Steps to Reproduce**
Select send and  scan QR.
Select send shielded and scan QR.

**Expected Result**
Once address was recognized, application should change the view back to the view for sending CCDs. Address should be inserted into the address field and transfer can be carried out.
Same result is expected for shielded transfers.

**Actual Result**
After QR code was scanned, it seems that application keeps hanging. It is possible to select back and address would be there but it seems that address is not valid while it matches the one that was scanned.

Video
https://user-images.githubusercontent.com/98821384/157415735-c95b50df-1da0-4087-9223-edc0973b9b8b.mp4

**Versions**
- Software Version: Testnet 2.0.0 (36)
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE

**Comment by concordium-cl** [comment]
Verified in CCD app 2.0.0 (38), iPhone 11, iOS 15.1.
