### ISSUE TITLE
Toggle should be "pressed down" when the tab is selected

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#220]
**Bug Description**
Selected tab is highlighted while it should be grayed (pressed down) when the tab is active.
This should be teh same as implemented on Android version 2.0.1 (71)

**Steps to Reproduce**
Show shielded balance.

**Expected Result**
Shielded balance view should appear and the tab should look as it was pressed down. It should look the same as on Android MW.

**Actual Result**
It looks the opposite compared to implementation on Android MW.

Image:
![toggling](https://user-images.githubusercontent.com/98821384/157007374-1aee3020-fff3-490d-a7c5-099f42085e25.png)

**Versions**
- Software Version: Testnet 2.0.35
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE

**Comment by ruxandra-constantinescu** [comment]
@mh-concordium Current iOS implementation is aligned with the wireframes. @jens-concordium Can you clear this?
<img width="380" alt="image" src="https://user-images.githubusercontent.com/67324897/157452858-9d34d831-a8bc-4c38-803e-0e3d64326ee6.png">

**Comment by jens-concordium** [comment]
@ruxandra-constantinescu, yep, sorry,  I forgot to mention that at the status. The Android version had accidentally been implemented "the wrong way around", but after testing it, it turned out to actually seem more clear that way. So we ended up deciding to go with that way instead.

**Comment by mh-concordium** [comment]
**Versions**
- Software Version: Testnet 2.0.0 (37)
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE

**Comment by concordium-cl** [comment]
Verified in CCD app 2.0.0 (38), iPhone 11, iOS 15.1.
