### ISSUE TITLE
Total balance is wrong in send funds view

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#221]
**Bug Description**
While sending CCDs with regular transfer, it seems that total balance still includes Shielded balance.

**Steps to Reproduce**

- Create new ID/Account.
- Request 2000 CCDs.
- Shield 500 CCDs.
- Send 2 CCDs with simple transaction.
- Observe balances in Send Funds view.

**Expected Result**
Total on the Send Funds view includes Shielded amount.

**Actual Result**
Shielded amount is separated.

Video:

https://user-images.githubusercontent.com/98821384/157449151-de02d8e7-9459-473a-a8d5-5aa9629f818f.mp4

**Versions**
- Software Version: Testnet 2.0.0 (36)
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE

**Comment by concordium-cl** [comment]
The same for shielding instead of sending. Idk if that is the same fix.

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: Testnet 2.0.0 (37)
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE
