### ISSUE TITLE
Show shielded balance from burger menu doesn't prompt user for password

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#228]
**Bug Description**
This issue appeared after Concordium backup file was imported and it contained shielded amount of CCDs. After the file was imported and user selects show shielded amount, application switches to shielded balance but just shows 0. If user attempts to switch between balance tabs, application prompts for password and only then shielded amount is visible correctly.

**Steps to Reproduce**

1. Install current version of the application.
2. Create account that has shielded amount and export Concordium backup file
3. Import Concordium backup file created on the current version to the application version that is to be released.
4. Select burger menu -> show shielded balance

**Expected Result**
User is prompted for password, after correct password was provided, application shows accurate shielded balance.

**Actual Result**
Shielded balance is visible but it equals to 0 no matter what is the real shielded balance value is. However, if user selects balance tab and then afterwards shielded balance tab, user is prompted for password. After, that shielded balance is correctly presented.

Video:

https://user-images.githubusercontent.com/98821384/158256354-39bd8607-d1f9-4102-be8f-256fd9506945.mp4

**Versions**
- Software Version: Testnet 2.0.0 (37)
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE

**Comment by concordium-cl** [comment]
Verified in CCD app 2.0.0 (38), iPhone 11, iOS 15.1.
