### ISSUE TITLE
Store account randomness securely in database

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#23]
**Task description**
In the future, users should be able to reveal more attributes on their accounts at a later time than on account creation. To enable this, the randomness used to reveal attributes on account creation must be saved in the database so it can be accessed later. 

**Requirements:**

- The mobile wallet saves the randomness for new accounts in the database in a secure way.
- The randomness can be accessed later, so people can reveal more attributes on their account. We should also have the option to access the randomness for potential future off-chain use-cases.
- The new version of the mobile wallet must be able to handle “old” accounts created before the randomness could be saved in the database. 
- The export/import feature must support the saved randomness.

**Notes:**

- The randomness is secret material so it must be handled in a secure way, on par with account keys  and IdCredSec.
- The response from createCredential from the library supplied by Concordium, has an additional field commitmentsRandomness.

**Comment by jens-concordium** [comment]
@kristiyandobrev, @concordium-cl, @abizjak  

Findings from testing:
- When checking an export from the iOS wallet v1.0(15), there does not seem to be any randomness saved with the accounts. The accounts were newly made on Testnet. 
- The format of the export also seems to have been changed, as the metadata field is now missing.

**Comment by kristiyandobrev** [comment]
@jens-concordium 

1.0(15) does not include the randomness.

**Comment by jens-concordium** [comment]
@kristiyandobrev,

Ah, I see. Then it makes sense it's not here!

**Comment by jens-concordium** [comment]
Verified in v1.0(16).
