### ISSUE TITLE
Transaction slip is missing info

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#243]
**Bug Description**
It seems that transaction slip will only contain information about the updated parameters. So for example, if the only update user did was increasing delegated CCDs from 100 to 150, the only information in the transaction slip will be the CCD amount. I believe it is still beneficial for the user to show the target pool and if rewards are added to the delegation or not. On this way, user gets certainty about where the funds will be delegated.

I have also presented and discussed this issue with @jens-concordium and we agreed this is beneficial to have. 
At the end, the example in Figma from Flow 3, Scenario 1 shows that only delegation amount was decreased but still all other information like target pool and rewards were shown.

**Steps to Reproduce**
Update delegation (increase or decrease stake) -> Observer transaction slip.
Stop delegation  -> Observer transaction slip.

**Expected Result**
Target pool and reward status should always be shown on the transaction slip.

**Actual Result**
Target pool and reward status is shown only if those parameters were updated.

**Versions**
- Software Version: 3.0.0 (39)
- OS:14.8.1
- Browser
- Mobile device: iPhone SE

**Comment by ruxandra-constantinescu** [comment]
@mh-concordium Wouldn't the user then believe that the transaction updates those as well?
But it is only "target pool" and "restake" options that will be always be shown and NOT the amount (in case that is not changed)?

**Comment by mh-concordium** [comment]
Discussed with Mikael. Works as intended.
