### ISSUE TITLE
Accounts do not show in address book

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-reference-wallet-ios#25]
**Bug Description**

In some cases, accounts are not added to the address book when they are created, or when they are imported. See support ticket SUPPORT-331.

**Steps to Reproduce**

Unclear. It is possible that this is a result of an initial account not being created correctly.

**Expected Result**

Accounts in the account list should also appear in the address book.

**Actual Result**

Accounts do not appear in the address book.

**Versions**
- Software Version 1.0.4
- OS
- Browser
- Mobile device, if applicable

**Comment by concordium-cl** [comment]
Closed for now as not reproducible.
