### ISSUE TITLE
Delegated amount "hangs" on the Shielded balance tab

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#251]
**Bug Description**
If user has both Delegated amount and shielded amount, it seems that tab transition between the balance tab and shielded balance tab is not smooth.
Delegated amount seems to "reside"  on the Shielded balance tab for almost a second before it actually vanishes.

**Steps to Reproduce**
1. Request 2000 test CCDs.
2. Delegate 1000 CCDs to L-pool.
3. Shield 500 CCDs.
4. Switch between Balance tab and Shielded  balance tab.

**Expected Result**
Smooth transition between tabs, balances change accordingly.

**Actual Result**
Delegated amount seems to "reside"  on the Shielded balance tab for almost a second before it actually vanishes.

Another strange outcome happens that application keeps loading after switching tabs multiple times. Loading wheel keeps spinning. This sometimes happen after switching 4 times, sometimes 8 times so it appears occasionally.

**Versions**
- Software Version: 3.0.0 (40)
- OS:14.8.1
- Browser
- Mobile device: iPhone SE

Video attached:

https://user-images.githubusercontent.com/98821384/164469719-5f77f6c8-5025-4ede-9d16-6be43e86b281.MP4

**Comment by mh-concordium** [comment]
Another video where application just keeps loading.

https://user-images.githubusercontent.com/98821384/164518754-5a0b5493-269d-436b-aa6f-92e7a7f6544f.MP4

**Comment by mh-concordium** [comment]
It seems that transition from Balance tab  to Shielded balance tab is now smoothen out. However, it seems that there is a loading wheel working all the time on the bottom of the tx log.

https://user-images.githubusercontent.com/98821384/168657548-dcd70d35-c01d-4033-a458-6c5606e2d4a9.mp4

Verified.
Wallet version: 3.0.0 (42)
iOS: 15.4.1
Device: iPhone SE

**Comment by ZB-concordium** [comment]
Verified.
Wallet version: 3.0.0 (44)
iOS: 15.5
Device: iPhone SE
