### ISSUE TITLE
Amount available for updated delegation amount is incorrectly calculated

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#252]
**Bug Description**
When updating the amount of an existing delegation, the available amount should not only be the "at disposal" amount. The amount that is already locked in a delegation can also be used when setting the new amount. Only the fee for making the transaction have to be taken from the "at disposal" amount.

So in short: The delegation amount can be taken from the full public balance incl. what is already locked in delegation, but the fee has to be available from the "at disposal" amount. 

**Steps to Reproduce**
Pre-requisite: Fresh account with 2000 CCD.
1. Set up a delegation with 1500 CCD.
2. Notice how the at disposal is now 500 (which is correct). 
3. Try to update the delegation amount to be 1600, but notice how there is not enough funds.
4. ![IMG_F21509134471-1](https://user-images.githubusercontent.com/76045015/164673535-2798e3d4-4a35-4fe7-bedd-1e467ca2478d.jpeg)

**Expected Result**
It's possible to delegate the full public balance minus the fee. 

**Actual Result**
It's only possible to update delegation amount to whatever is at disposal.

**Versions**
- Software Version: 3.0.0(40)
- OS: iOS

**Comment by mh-concordium** [comment]
Verified.
- Software Version:  3.0.0 (42)
- OS: iOS 15.4.1
- Mobile device: Device: iPhone SE
