### ISSUE TITLE
Cancel option missing from dialog

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#26]
**Description**
Hashed sessionID functionality: When id issuing fails, user should be able to cancel, probably by extra button. Note this is not in the original feature scope but commented on later in the feature proposal. Also note that explanation in text to click outside of dialog, as suggested in feature proposal, does not work in iOS.

**Expected Result**
Dialog has buttons 
* Try again
* Contact Support
* Cancel

**Actual Result**
Dialog has buttons 
* Try again
* Contact Support

**Versions**
* Concordium Testnet Wallet v1.0(14)
* iPhone 11, iOS 14.5.1

**Comment by kristiyandobrev** [comment]
I believe this was fixed by https://github.com/Concordium/concordium-reference-wallet-ios/pull/39.

**Comment by concordium-cl** [comment]
Tested w/ https://github.com/Concordium/concordium-reference-wallet-ios/issues/36
