### ISSUE TITLE
Update text vol 2

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#268]
**Task description**

There are three screens that needs to have their texts updated again. Two of the screens are in the introductory delegation carousel, and the third one is the one where the user can decide between a specific baker pool or passive delegation. 

The new text is highlighted in blue, in the box called "Renaming of L-pool to passive delegation VOL 2 in Figma. It can be seen on to the right of the first renaming box.

**Comment by EmilLa1** [comment]
3.0.0 (48)

1. 'Delegation Models' Is not looking really good right now. See https://github.com/Concordium/concordium-reference-wallet-ios/issues/285
2. 'Passive Delegation' Looks good
3. 'Update Delegation'. -> Passive. Text is not the same as on Figma. https://github.com/Concordium/concordium-reference-wallet-ios/issues/286
