### ISSUE TITLE
Informing user regarding funds released after the cooldown period

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#270]
**Bug Description**
If an user reduced the delegation amount or removes funds completely from a pool. User will enter the cooldown period that lasts for "delegator cooldown duration". However, funds are actually released on the next payday. Meaning, funds are released for "delegator cooldown duration" + time to next payday.

**Steps to Reproduce**
Remove delegation.
Reduce the delegated stake.

**Expected Result**
Inform the user about releasing funds after the correct time.

**Actual Result**
Only cooldown time is shown to the user.

**Versions**
- Software Version:  3.0.0 (42)
- OS: iOS 15.4.1
- Mobile device: Device: iPhone SE

**Comment by EmilLa1** [comment]
3.0.0 (48) 
The time on delegation status page for 'stopping delegation' is correct.
