### ISSUE TITLE
Delegation carousel has a typo on page called Baker pools

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#272]
**Bug Description**
![image](https://user-images.githubusercontent.com/98821384/169105573-f12d9ffb-c123-48b7-a0e1-6d2237cad454.png)

**Steps to Reproduce**
Try to start Delegation with an account that doesn't have active Delegation.

 **Expected Result**
Expected text as described in Figma.

**Actual Result**
See Description.

**Versions**
- Software Version:  3.0.0 (42)
- OS: iOS 15.4.1
- Mobile device: Device: iPhone SE

**Comment by ZB-concordium** [comment]
Verified.
Wallet version: 3.0.0 (44)
iOS: 15.5
Device: iPhone SE
