### ISSUE TITLE
The status page claims, next you will se the status page which is not the case

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#273]
**Bug Description**
Last page in carousel is The status page. On that page it is written that next page will be Delegation Status page from which user can start Delegation. This is not true, after selecting continue, user is redirected directly to Register Delegation page. Therefore, it is required to just change the text on the last page of the carousel.

**Steps to Reproduce**
Attempt to start Delegation
Slide through Delegation carousel
Pay attention to text on the last page of the carousel

**Expected Result**
Text:
Next you will be able to start delegation.
After you started delegation, status page will show you your delegation status. You will be able to make updates to your delegation from the status page.

**Actual Result**
Text:
Next you will see the delegation status screen. 

From there you will be able to start your first delegation, make updates, and see the current status. 

**Versions**
- Software Version:  3.0.0 (42)
- OS: iOS 15.4.1
- Mobile device: Device: iPhone SE

**Comment by ZB-concordium** [comment]
![20220530_115117](https://user-images.githubusercontent.com/105038149/170967249-0098aaa3-608f-4dbf-8b7d-65e317a84c58.jpg)

**Comment by Niljak** [comment]
This issue has already been fixed in later versions of the app, therefore I'm moving it to Ready to Test

**Comment by Niljak** [comment]
> > This issue has already been fixed in later versions of the app, therefore I'm moving it to Ready to Test
> 
> I tested in version 3.0.0 (44), is there a newer one?

No, sorry, I misinterpreted the message. It's been corrected and will be available in the next release

**Comment by EmilLa1** [comment]
3.0.0 (48) 

Text is not as 'Expected'. 

Moreover there is a spelling mistake. I believe it should be 
... "able to see **its** current status"....
Instead it's currently: 
... "able to see **it's** current status"....

**Comment by EmilLa1** [comment]
@Niljak My mistake. I believe I looked at the wrong place in Figma. Your link looks correct.

**Comment by EmilLa1** [comment]
Looks good. 
3.0.0(49)
