### ISSUE TITLE
Register delegation transaction slip

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#274]
**Bug Description**
When registering delegation, transaction pay slip will appear before the transaction is sent.
This slip contains text:
"You are about to submit a delegation transaction. This will lock your delegation amount for at least X days."
Please change the text to:
"This will lock your delegation amount. Amount is released after X days from the time you remove or decrease your delegation."

**Steps to Reproduce**
Register Delegation, observe transaction pay slip.

**Expected Result**
"This will lock your delegation amount. Amount is released after X days from the time you remove or decrease your delegation."

**Actual Result**
"You are about to submit a delegation transaction. This will lock your delegation amount for at least X days."

![image](https://user-images.githubusercontent.com/98821384/169109281-d25b553f-d98e-430e-b01f-46da1903d6ef.png)

**Versions**
- Software Version:  3.0.0 (42)
- OS: iOS 15.4.1
- Mobile device: Device: iPhone SE

**Comment by ZB-concordium** [comment]
Verified.

Software Version: 3.0.0 (44)
OS: iOS 15.5
Mobile device: Device: iPhone SE
