### ISSUE TITLE
Link to documentation is missing

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#275]
**Bug Description**

**Steps to Reproduce**
Documentation link is missing on Register delegation page, no matter if valid id is inserted or Passive Delegation is selected, the link to documentation is missing.

**Expected Result**
There should be link to official documentation as it is accessible on other pages such as Delegation carousel. 

**Actual Result**
![image](https://user-images.githubusercontent.com/98821384/169111488-3dbc6912-c6b8-47e5-94f4-1482c1fb2723.png)

**Versions**
- Software Version:  3.0.0 (42)
- OS: iOS 15.4.1
- Mobile device: Device: iPhone SE

**Comment by ZB-concordium** [comment]
Verified.

Software Version: 3.0.0 (44)
OS: iOS 15.5
Mobile device: Device: iPhone SE
