### ISSUE TITLE
First batch of CRs from the UATs

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#277]
**Task description**
We got a handfull of findings from the user acceptance tests done on the mobile wallet, and some of them has lead to some small changes that should go into the Sirius release. The changes can be found in Figma, in the box called "First batch of CRs from the UATs". The changes are found across three flows:

1. Removal of “Send all” and add a 95% warning on the shielding transaction. Currently there is a "Send all" button on the "Shielding" transaction, and it should be removed as it can lead to people locking all their funds in their shielded balance by mistake. Additionally we want to show a warning, when the user presses "Shield amount", while having entered more than 95% of their at disposal amount.

2. The links in the delegation carousel should be updated, and two minor textual changes should be made. All changes are marked in a blue color in the flow, and the changes are also noted beneath each of the screens.

3. The screen that lets the user decide between a specific baker pool or passive delegation has some minor textual changes. When the "Baker" option is chosen, the text in the input field should be changed, the text below the input field should be changed a little bit, and the link should be active with the URL supplied. The same goes for the link shown, when the "Passive" option is chosen.

**Comment by EmilLa1** [comment]
3.0.0 (48) 

1. There is no 'Send all' button. A warning is displayed if one tries to stake 95% or more of total capital.
2. The texts now uses 'passive delegation'.
3. Links are active.
