### ISSUE TITLE
Add the "Earn" button to the UI

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#278]
**Task description**

This tasks includes a few changes:
- The Delegation and Baking options should be removed from the current burger menu dropdown.
- The account card now has an “Earn” button.
- The account details page now has an “Earn” button. This means that there are now three buttons on the account details page with no shielded balance enabled, and four buttons on the page if the shielded balance is enabled. The shielded balance tab still only has three buttons, as delegation / baking is unrelated to that balance.
- Pressing the earn button from any place will show a new dropdown, that shows both Delegation and Baking.

Clarifications:
- The "Earn" button is a common button for delegation and baking, that brings both features forward in the UI, so the user doesn't have to browse all the way into the account details' drop down menu. 
- If the account is neither baking, nor delegating, the Delegation and Baking buttons will take the user to either of the intro carousels, like they did in the previous dropdown. 
- Once the user has started either delegating or baking, both buttons will stay in the new dropdown. If the user then presses the baking button while already delegating, they will be met with a notification saying they can’t do both at the same time, and vice versa. 

The changes can be seen in Figma on the page called "Second batch of CRs from the UATs". Ask @jens-concordium if you can't find them.

**Comment by concordium-cl** [comment]
Done.
