### ISSUE TITLE
Same failure dlg on both account card and identity card page

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#28]
**Description**
Hashed sessionID functionality: The failure dialogs differ, depending if account or identity page is open.

**Expected Result**
On account page:
* Contact support
* Try again

On identity page
* Contact support
* Try again

**Actual Result**
On account page:
* Contact support
* Ok (which behaves as "try again)

On identity page
* Contact support
* Try again

**Versions**
* Concordium Testnet Wallet v1.0(14)
* iPhone 11, iOS 14.5.1

**Comment by kristiyandobrev** [comment]
This was fixed by https://github.com/Concordium/concordium-reference-wallet-ios/pull/39

**Comment by concordium-cl** [comment]
Tested w/ https://github.com/Concordium/concordium-reference-wallet-ios/issues/36
