### ISSUE TITLE
Delegation Status - Waiting for transaction to finalize

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#280]
**Bug Description**
While adding/updating/removing delegation, if transaction was not finalized, we would see the status page with text "Waiting for transaction to finalize". The problem is that even if transaction gets finalized, status page will not change.
This could make users wait for a long time or thinking that transaction can't be finalized. I believe this will often happen if internet connection is slower or proxy doesn't respond for some reason.

**Steps to Reproduce**
Add delegation -> Submit -> Insert passcode -> Finish -> Confirm dialogue -> Burger menu -> Delegation. 

Such a screen can be visible if user tries to see the Delegation status page while transaction was not finalized after following actions:
- Add delegation.
- Update delegation stake.

**Expected Result**
After transaction was finalized, Delegation status page should be changed accordingly. User should not select back and forth to see the change in the status page, rather page will be changed automatically once the transaction is finalized.

**Actual Result**

https://user-images.githubusercontent.com/98821384/171373721-c129951f-0455-4921-8f2e-24026844552d.mp4

**Versions**
- Software Version: 3.0.0 
- OS: Android
- Browser
- Mobile device: 

NOTE: This issue was discovered on Android

**Comment by Niljak** [comment]
Fixed in build 46

**Comment by mh-concordium** [comment]
Verified in 3.0.0 (48)
