### ISSUE TITLE
Add baker with empty URL fails

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#281]
**Bug Description**
Add baker with empty URL fails.

**Steps to Reproduce**
Add baker, leave URL empty.

**Expected Result**
This should be possible.

**Actual Result**
Transaction fails
**Versions**
- Software Version: 3.0.0(47)
- OS: iOS

**Comment by Niljak** [comment]
Fixed in build 48

**Comment by mh-concordium** [comment]
Verified in 3.0.0(48)
