### ISSUE TITLE
Show total staked amount for a pool with delegators.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-reference-wallet-ios#283]
**Description**

On the 'baker status' page the baker can only see its own stake but not the stake from delegators.

**Steps to Reproduce**

- Become a baker with an open pool.
- Delegate to the baker pool
- Open the 'baker status' page.

**Expected Result**
I would expect that the baker owning the pool should also see stake from delegators. 

**Actual Result**
Only the baker stake is visible.

**Versions**
- Software Version 3.0.0 (48)
- OS iOS

**Comment by jens-concordium** [comment]
@EmilLa1, yep that is a good idea. I think we'll have to save it for the later release, as we are getting quite close now.

**Comment by concordium-cl** [comment]
Will move to jira.
