### ISSUE TITLE
Notification after delegator moved to PassivePool due to old pool shutdown.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-reference-wallet-ios#284]
**Description**

As per https://github.com/Concordium/concordium-reference-wallet-ios/issues/253 the delegator receives a notification that the current pool is closing everytime the app is launched. 

It could also be beneficial to notify the user **after** the move to the passive pool has taken place. 

**Versions**
ios 3.0.0 (48)

**Comment by concordium-cl** [comment]
Would require substantial changes. Not in scope. Won't do.
