### ISSUE TITLE
Weird text display in 'Delegation Models'.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-reference-wallet-ios#285]
**Bug Description**
Some of the text is being displayed incorrectly. 

Also the last paragraph have some weird formatting.

See screenshot. 

**Steps to Reproduce**

Start the delegation flow and follow the carousel. 

**Expected Result**
No weird typos.

**Actual Result**
See screenshot.

**Versions**
iOS 3.0.0 (48)
![File](https://user-images.githubusercontent.com/39825288/174294889-bf844202-8370-45ea-a3b3-b00095910cc7.jpg)

**Comment by EmilLa1** [comment]
@jens-concordium

**Comment by jens-concordium** [comment]
@EmilLa1 I think it's just some problems with the apostrophes in some of the words. 

@mh-concordium, did you already do something about this? If not @EmilLa1 has registered it here

**Comment by Niljak** [comment]
Fixed in version 3.0.0 (49)

**Comment by EmilLa1** [comment]
The apostrophes are fixed. 
@jens-concordium Nitpicky. But the last two lines aren't really that good looking? Too much spacing?

**Comment by EmilLa1** [comment]
Ok. Will close for now then.
