### ISSUE TITLE
Delegator is not informed on status page that pool was removed

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#287]
**Bug Description**
If delegator has a stake in a baker pool that was removed, delegator should see warning on the Delegation Status page.
 
**Steps to Reproduce**
Delegate to Baker 1
Remove Baker 1
Open Delegation Status page

**Expected Result**

Screenshot taken from Android implementation:

![image](https://user-images.githubusercontent.com/98821384/174781587-6ec50d0d-829a-4b31-a585-fb2880e2fe8a.png)

**Actual Result**
Delegator doesn't see warning as on screenshot.

**Versions**
- Software Version: 3.0.0 (48)
- OS: iOS

**Comment by Niljak** [comment]
Fixed in 3.0.0 (50)

**Comment by EmilLa1** [comment]
Looks good in 3.0.0 (51)
