### ISSUE TITLE
Delegating scheduled CCDs

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#288]
**Bug Description**
Issues below were initially discovered on Android. This bug was created to make sure we verify the fix on iOS as well. 
Fix will be provided in 3.0.0 (50).

**Steps to Reproduce**
Issue 1:
If you have staked/delegated your 500 CCDs that were at disposal, you will end up with 0 at disposal and 500 staked. Then, afterwards you receive 500 CCDs via scheduled transfer, you should have 500 at disposal because those which are scheduled should be staked/delegated first. 

Issue 2:
If you have 500 CCDs at disposal and 500 CCDs scheduled, if you delegate 900, you should have 100 at disposal (- tx fee).
**Expected Result**

**Actual Result**
See issues above.

**Versions**
- Software Version:3.0.0 (49)
- OS: iOS

**Comment by EmilLa1** [comment]
1. Looks fine 
2. Looks fine
3.0.0 (51)
