### ISSUE TITLE
Create identity button doesn't work

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#289]
**Bug Description**
If my identity creation failed. I will see Account page as attached below.

**Steps to Reproduce**
Install fresh Testnet app.
Use Notabene in attempt to create ID.
Make it fail (I used Passport example found on internet).
After failed ID, Accounts page will appear.
Select "Create identity" button.

**Expected Result**
Button should initiate create identity and initial account flow.

**Actual Result**
![image](https://user-images.githubusercontent.com/98821384/175006470-da525573-dfe6-4a9a-8234-7ffe3e0a6777.png)

Button doesn't work.

**Versions**
- Software Version: Testnet app 3.0.0 (47)
- OS: iOS 15.5
- Mobile device, if applicable: iPhone SE

**Comment by Niljak** [comment]
Fixed in 3.0.0 (51)

**Comment by mh-concordium** [comment]
Verified in 3.0.0 (52).
