### ISSUE TITLE
After sessionID is sent via failure dialog, clicking on failed account crashes the app.

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#29]
**Description**
Hashed sessionID functionality: On account page, after sessionID is sent via failure dialog, clicking on failed account crashes the app.

Steps to Reproduce:
* in failure dialog on account page (not identity page), “contact support”
* sent support e-mail with sessionID to NB
* initial account marked as failed
* clicking on failed account crashes the app

**Expected Result**
No crash.

**Actual Result**
Crash.

**Versions**
* Concordium Testnet Wallet v1.0(14)
* iPhone 11, iOS 14.5.1

**Comment by jens-concordium** [comment]
Findings from testing:
The initial account is removed as intended now, so it's not possible to press it, thus solving the problem.
