### ISSUE TITLE
Delegation status is not functional.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-reference-wallet-ios#290]
**Bug Description**

- The delegation view is not functional on the newest version 

**Steps to Reproduce**

Register delegation.
Go to the Delegation Status page. (After the transaction is finalized) 

**Expected Result**
See the delegation status page with various delegation related information.

**Actual Result**
![File (2)](https://user-images.githubusercontent.com/39825288/175049308-b2959f91-1d34-42df-837a-78df3ac7c60e.jpg)

**Versions**
3.0.0 (50)

**Comment by Niljak** [comment]
Fixed in 3.0.0 (51)
