### ISSUE TITLE
Application crash on "failed ID -> Try again"

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#292]
**Bug Description**
If the ID creation failed, user gets dialogue with three options: "Try again", "Contact support", "Cancel". If user selects "Try again" application crashes.

**Steps to Reproduce**
In attempt to create new ID, make creation with Notabene failed.
Wile waiting for ID to be valid (pending validation), just wait while observing Accounts page.
After the dialogue appears select "Try again".

**Expected Result**
Create ID flow should be reinitiated.

**Actual Result**
Application crashes.

https://user-images.githubusercontent.com/98821384/175103379-c0332998-627a-4303-9cbe-d342dfe1f6d4.mp4

**Versions**
- Software Version: Testnet app 3.0.0 (50)
- OS: iOS 15.5
- Mobile device, if applicable: iPhone SE

**Comment by Niljak** [comment]
I've managed to find the cause for this issue, and several other similar issues that boil down to the same problem: Once an identity is deemed invalid we remove related accounts from out database. Our database objects are what are called "live objects" so they auto update when the database changes, but if you try to access them after they are removed the app crashes. The crash you are seeing is a result of this. There are ways to mitigate this by verifying that objects have not been removed before access, but doing this in every case is a very big task. I would worry that implementing it would break more things than it fixes, so it might be worth pushing this issue until after 3.0.0.

**Comment by jens-concordium** [comment]
Yep, agreed. Let's wait.

**Comment by concordium-cl** [comment]
Other related issues in jira.
