### ISSUE TITLE
Transaction Details - Transaction submitted typo.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-reference-wallet-ios#293]
**Bug Description**
If a transaction has yet to be finalized and is in `submitted` status

**Steps to Reproduce**

- Send a transaction 
- Click the transaction (before it is finalized)
- Observe the text in the 'Block Hash' field.

**Expected Result**
'Submitted'

**Actual Result**
'Submitte'

**Versions**
3.0.0 (49)

**Comment by concordium-cl** [comment]
Known issue but worth fixing when time allows. Will moved it to backlog.

**Comment by concordium-cl** [comment]
Copied to https://concordium.atlassian.net/browse/CBW-219
