### ISSUE TITLE
ID creation fails after upgrading app from 2.0.0 to 3.0.0

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#294]
**Bug Description**
It seems that ID creation fails with both ID providers after app was updated from 2.0.0 (39) to 3.0.0 (52).

**Steps to Reproduce**
Install latest 2.0.0 MW, which is currently 2.0.0 (38).
Create ID with DTS, request 2000 CCDs and shield 500.
Open TestFlight and update to the latest MW, 3.0.0 (52).
Create new ID with DTS.
Create new ID with Notabene.

**Expected Result**
New IDs and initial accounts should be created.

**Actual Result**
ID creation fails.

![image](https://user-images.githubusercontent.com/98821384/175947965-b9cd2bb0-342e-4a33-8aa0-aeae8d24e27d.png)

**Versions**
- Software Version: Testnet 3.0.0 (52)
- OS: iOS 15.5

**Comment by Niljak** [comment]
Ran through the scenario on my own device and it works just fine (I'm assuming this is done on Testnet). The page you end up on is only shown if we receive a bad response from the server so I would guess that the IDP had an issue.

**Comment by mh-concordium** [comment]
I was able to get the ID created if I have only installed 3.0.0, but if I did an upgrade from 2.0.0, then it failed.
First it failed 4 times in a row, then I deleted app, installed 3.0.0 again and it worked. Afterwards, I have installed 2.0.0 and upgraded to 3.0.0 and it didn't work again. So it was really pointing to failure that is strictly related to upgrading from 2.0.0 -> 3.0.0.

I guess I could try to reproduce it tomorrow again.

**Comment by Niljak** [comment]
My test included the upgrade scenario, and I could create IDs just fine. So it's either the ID providers or something else in your setup that triggers it.

**Comment by mh-concordium** [comment]
It consistently fails on my iPhone as I described. I have just tried it now again.
Did you use Biometrics? Initially, I didn't mention that because I didn't know it matters but now I am trying to figure out what are we doing differently.

**Comment by mh-concordium** [comment]
@Niljak I have tried without a fingerprint and it worked for me as well.
Please try to enable unlock with fingerprint and repeat the test if you didn't already.

**Comment by Niljak** [comment]
Fixed in version 3.0.0 (53)

**Comment by concordium-cl** [comment]
- EmilB verified fix on iPhone SE.

**Comment by concordium-cl** [comment]
Verified in 3.0.0 (53).
