### ISSUE TITLE
"Current delegation amount too large" notification shown on current target baker

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#295]
**Bug Description**
If an account currently has an active delegation with a baker pool, and the baker pool is so close to it's limit, that the account would not be able to increase it's delegation amount without bringing the pool over it's limit, the notification in the screenshot will be shown. 

The notification is only meant to be shown in case the account is changing target pools, so in the scenario where the account stays with the same pool, the notification should not be shown.

![IMG_C3C9A2C438A2-1](https://user-images.githubusercontent.com/76045015/176119803-31831103-e6ec-42d6-bc08-482afc072271.jpeg)

**Steps to Reproduce**
1. Have a baker pool.
2. Make another account delegate enough to take the baker pool from step 1 to it's limit.
3. Try to go and update the delegation amount, and notice how the notification is shown, even though another target pool has not been entered.

**Expected Result**
No notification.

**Actual Result**
The notification is shown.

**Versions**
- Software Version: 3.0.0(52)
- OS: iOS 15
- Mobile device: iPhone XS

**Comment by concordium-cl** [comment]
Copied to https://concordium.atlassian.net/browse/CBW-217
