### ISSUE TITLE
Incorrect on delegation status screen

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#298]
**Bug Description**
After setting up delegation in the iOS wallet, one the titles on the delegation status screen says "Account to delegate from". This is meant to be "Delegating account". The text "Account to delegate from" is meant to be used on the transaction slips show when submitting the transaction only.

![IMG_BF2A5F09A7F5-1](https://user-images.githubusercontent.com/76045015/176695157-97cf0466-c950-4b8f-ab79-0be10f2f35e9.jpeg)

**Steps to Reproduce**
- Set up delegation on an account.
- Check status page, and notice how the text says "Account to delegate from".

**Expected Result**
Text says "Delegating account"

**Actual Result**
Text says "Account to delegate from"

**Versions**
- Software Version: 3.0.0(53)
- OS: iOS 15.x
- Browser
- Mobile device: iPhone XS

**Comment by concordium-cl** [comment]
Copied to https://concordium.atlassian.net/browse/CBW-218
