### ISSUE TITLE
Register delegation shows 0 days of cooldown

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#299]
**Bug Description**
If there has been made no "Update delegation" transactions from the iOS mobile wallet, the screen showing the transaction overview before submission of "Register delegation" transactions will show 0 days of cooldown. 

NOTE: It has be Testnet or Mainnet, to be sure the cooldown is actually set to 14 days as expected.

**Steps to Reproduce**
1. Have two accounts with money on the iOS mobile wallet, non of which should be delegating.
2. Start the register delegation flow on the first account, and notice how it mentions 0 days of cooldown on the submission screen. You can repeat this step a few times without actually submitting the transaction, to see that the 0 is consistent.
3. Register a delegation on one of the accounts.
4. Try to repeat step 2 with the second account, and see that it still says 0.
5. Update the delegation on the first account from step 3. Increasing the amount should be just fine. Wait for the transaction to finalize.
6. Try to add a delegation on the second account, and notice how it now says the correct amount of days (14 on Mainnet and Testnet).

![IMG_A666126A9FDE-1](https://user-images.githubusercontent.com/76045015/177953075-87dc6738-fe21-4dc0-a6e7-be8ae0bb5834.jpeg)

**Expected Result**
The correct amount of cooldown days is shown on the submission screen.

**Actual Result**
0 days of cooldown is shown on the submission screen.

**Versions**
- Software Version: 3.0.0(53) - It has to be Testnet, to be sure the cooldown actually is 14 days.
- OS: iOS 15.2
- Mobile device: iPhone XS

**Comment by concordium-cl** [comment]
Github bug will be closed; further development to be followed in (internal) jira: [CBW-220](https://concordium.atlassian.net/browse/CBW-220)
