### ISSUE TITLE
Leaving app while waiting for id issuing (to fail) and then returning on account page crashes the app.

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#30]
**Description**
Hashed sessionID functionality: Leaving app while waiting for id issuing (to fail) and then returning on account page crashes the app.

Steps to Reproduce:
* issued fake identity
* went to account page
* navigated away from app for a while
* came back to app on account page
* failure dlg was briefly shown
* app crashed 

**Expected Result**
No crash.

**Actual Result**
Crash.

**Versions**
* Concordium Testnet Wallet v1.0(14)
* iPhone 11, iOS 14.5.1

**Comment by jens-concordium** [comment]
Findings from testing:
This seems to be fixed, as the app doesn't crash when re-entering on the Account page. The will crash when browsing to the Identities page though, but I think that is related to the crash mentioned in the findings of #36
