### ISSUE TITLE
Old naming Concordium ID still present.

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#31]
**Description**
* When you delete app, dialog still stays remove “Concordium ID” instead of Concordium Testnet Wallet.
* In import dialog, app is also still called “Concordium ID”. 

**Versions**
* Concordium Testnet Wallet v1.0(14)
* iPhone 11, iOS 14.5.1

**Comment by jens-concordium** [comment]
@concordium-cl, @kristiyandobrev 

Findings from testing:
It longer says Concordium ID, but instead it says ProdTestNet both in the "delete app dialog" and below the app icon. Instead it should say Concordium Testnet Wallet.

**Comment by jens-concordium** [comment]
Verified as working in 1.0(16)
