### ISSUE TITLE
Camera mode controlled from app?

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#32]
**Task description**

**Sub-tasks**
- [ ] subtask 1
- [ ] subtask 2
- [ ] subtask 3

*Add label for component and priority.*

**Comment by kristiyandobrev** [comment]
That does not seems like an iOS issue. Since the camera is being opened from an external web page I guess that page dictates which "camera mode" wants to bring on screen.

**Comment by concordium-cl** [comment]
@kristiyandobrev, @jens-concordium: If I recall correctly, this was up for investigation and discussion?

**Comment by kristiyandobrev** [comment]
@concordium-cl: Absolutely, so my investigation concluded the above 👆

**Comment by jens-concordium** [comment]
@concordium-cl , @kristiyandobrev 

Yes, exactly. I also think we have pretty much concluded that we can't do anything.

**Comment by concordium-cl** [comment]
;-)
