### ISSUE TITLE
Wallet accounts missing on chain (iOS repo)

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#33]
**Bug Description**

We have received several support tickets where users have created identities and initial accounts successfully, i.e. identity and account cards look correct with green checkmark, but the account is not on the chain.

Examples:
* 3eMpGKfajwgzjUbfsVFou4ZoR3ALNYbe5w5VmNJ3LY5UoNXQsw
* 4ckJBDGyxMtRbXL3BAKscZkMDjxkXDLF4wKTaZjy29R2g87KEr
* 4miVxofGUV4AeXM3zauGwkbDxHUtvKhoxa1EpgicU7keZggj69

**Steps to Reproduce**
Unclear.

**Expected Result**
Either accounts fail or they can be found on chain.

**Actual Result**
Successful accounts cannot be found on chain.

**Versions**
- iOS 1.0.4

**Comment by concordium-cl** [comment]
See also https://github.com/Concordium/notabene/issues/14

**Comment by jens-concordium** [comment]
@concordium-cl 

There is also no real way to test and verify this, as we cannot reproduce it. Thomas' fix may also have helped here, but I think we also have to keep an eye out for new reports on this, to see if it has helped.
