### ISSUE TITLE
Aborted identity issuing flow creates identity card with unknown error

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#35]
**Bug Description**
When aborting the identity issuing flow at any point after having selected the IDP and before submitting the selfie, an identity card is created.  The usual error dialog pops up, allowing the user in the newest app version to send the hashed sessionID to Notabene. In such cases, Notabene will not be able to find the sessionID. The identity card gets status "failed" with reason "An unknown error occured creating identity. Please try again". 

Android does behave more correctly. There the identity card is not created until the selfie is submitted. Therefore, no error dialog is prompted to the user neither.

Note: In both iOS and Android, the "finish" button at the end of the flow is only meant to leave the identity flow.The identity is submitted by submitting the final selfie but before clicking the "finish" button.

**Steps to Reproduce**
- select IDP
- optional: complete some steps of the identity flow
- close the flow via the X in the right upper corner
- restart the app (close and open)

**Expected Result**
- No error dialog is shown.
- No identity card is created.

**Actual Result**
- Error dialog pops up. 
- In newest draft version of app, user can send hashed sessionID to Notabene. However, Notabene won't be able to find it.
- Identity card is created as "failed" with unknown error.

**Versions**
- Software Version: 1.0.4
- OS: iOS 14.5.1
- Browser: probably Safari
- Mobile device, if applicable: iPhone 11

![IMG_3621](https://user-images.githubusercontent.com/69570978/130443002-d781b3a1-e78d-44df-9da1-13271faad853.PNG)

**Comment by jens-concordium** [comment]
Findings from testing:
This seems to be fixed.
