### ISSUE TITLE
Identity object should be retrieved in the background (also when app is closed)

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#49]
[placeholder]

**Comment by jens-concordium** [comment]
I guess this tries to solve the same problems as the "new" last page of the identity issuance flow, letting the user know to check back once in a while. I've drawn up a few suggestions on what that last page could look like, but I think automatic retrieval would be a better solution. Maybe we should discuss what to do.

**Comment by concordium-cl** [comment]
This is a backlog placeholder for some future version, it is not in scope for the upcoming release. The last page is in scope now; created a new issue to be discussed with Mjoelner: https://github.com/Concordium/concordium-reference-wallet-ios/issues/52

**Comment by concordium-cl** [comment]
Context changed.
