### ISSUE TITLE
Incomplete initial account remains in account list after import of new wallet file.

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#5]
**Bug Description**
When initial account creation is initiated but then interrupted during the process to import an account file, the initial account appears in account list as pending. Clicking on it will give an error message. It cannot be deleted manually. 

First when another initial account is created, the broken initial account vanishes from account list.

[Reported originally in bug sheet as priority 2.]

**Steps to Reproduce**
- initiate initial account creation
- before selecting an identity provider, leave flow and import a wallet
- after import, inspect account list

**Expected Result**
Incomplete initial account should not be stored and shown in account list.

**Actual Result**
The initial account appears in account list as pending.

**Versions**
- Software Version v0.1.68
- OS: iOS 13.7
- Mobile device: iPhone11

**Comment by jens-concordium** [comment]
I just tested this on the 1.0.5 StagingNet build, and it seems to still be a problem and two slightly different scenarios. 

This was done on an iPhone XS with iOS 14.5. 

**What I did:**

Pre-requisites: Install the app, create a bunch of accounts and ID's, and then export them to use for testing.

_Scenario 1_
1. Reinstall the app.
2. Start making a new initial account and a new ID via the intro flow. Chose the Concordium ID provider, but minimize the app at the "external" flow.
3. Browse to  the file exported before, and open it with the StagingNet app. Nothing happens.
4. Close the "external" Concordium ID provider window with the x in the upper right corner.
5. Import again. This time it succeeds with the import, but it will say that the initial account creation failed. 
6.1 If Cancel is pressed on the toast, the initial account will stay there. If the "pending" initial account is pressed, the app will crash. Upon reopening the app, it will be gone. 
6.2 If "Try again" is pressed on the toast, the flow to make a new one will be started. It can either be finished or cancelled, and the "pending" initial account will be gone.

![IMG_5284](https://user-images.githubusercontent.com/76045015/122185569-7dba3d00-ce8d-11eb-8f0f-a4d530c0a2d6.PNG)


_Scenario 2_
1. Reinstall the app.
2. Start making a new initial account and a new ID via the intro flow. Minimize the app at the identity provider selection screen.
3. Browse to the file exported before, and import it into the app. Import will succeed.
4. The "pending" initial account from the intro flow will still be there, and no error toast is shown. 
5. Pressing the "pending" initial account will give an error message, saying that the app cannot connect to server. 
6. The initial account will stay there untill a new initial account is created.

![IMG_5287](https://user-images.githubusercontent.com/76045015/122185633-8743a500-ce8d-11eb-9ba9-229ba1f7ea96.PNG)
![IMG_5286](https://user-images.githubusercontent.com/76045015/122185639-890d6880-ce8d-11eb-8025-f4861b0e7e92.PNG)
