### ISSUE TITLE
Regression: Recent internal releases do not have the correct export format

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-reference-wallet-ios#50]
**Bug Description**

The export file should have the field `metadata` with contents such as
```json
    "metadata": {
        "initializationVector": "edJ0nmP\/cPVT1fJ+cbr4QQ==",
        "iterations": 100000,
        "salt": "DLOqKhBf\/P3NIy1Lahp2tOixWtU+ot83YlkU6arTpwQ=",
        "encryptionMethod": "AES-256",
        "keyDerivationMethod": "PBKDF2WithHmacSHA256"
    }
```

but instead the format is
```json
    "metadata": {
        "initializationVector": "edJ0nmP\/cPVT1fJ+cbr4QQ==",
        "iterations": 100000,
        "salt": "DLOqKhBf\/P3NIy1Lahp2tOixWtU+ot83YlkU6arTpwQ="
    }
```

**Steps to Reproduce**

Export a file from the wallet.

**Expected Result**

See above.

**Actual Result**

See above.

**Versions**
- Software Version: 1.0(16)

**Comment by abizjak** [comment]
@jens-concordium please add version number since you exported the files.

@kristiyandobrev not sure why this was changed at all, but it is critical functionality that is affected.

**Comment by jens-concordium** [comment]
I updated the report to include version number.

**Comment by abizjak** [comment]
It seems to be cause by this commit https://github.com/Concordium/concordium-reference-wallet-ios/commit/f287e2b41580ba3253f92453d2fe2c9388a9c167#diff-dbe20a501ac086b56fee70e24926060357f3f1db4c310489158c5fb9de50222fR10 making fields static.

**Comment by concordium-cl** [comment]
Verified in 1.0.18
