### ISSUE TITLE
Shielded transfers beyond first 20 are never loaded / has infinite loading bar

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-reference-wallet-ios#56]
**Bug Description**
Shielded transfers from beyond the 20 latest transactions on an account (including regular transactions) cannot be loaded. The wallet proxy returns at most 20 transactions per request, so it is shielded transfers from beyond the first request that is not shown.

**Steps to Reproduce**
1. Create a new account
2. Make a shielded transfer (incoming should work as well)
3. Make 20 transactions (shielded or unshielded)
4. Make a shielded transfer
5. View the shielded balance

**Expected Result**
All the shielded transfers should eventually be loaded and shown, including the one from step 2.

**Actual Result**
Shielded transfers among the latest 20 transfers (either shielded or unshielded) are shown, but the shielded transfer from step 2 is *not* shown.
Instead, a loading bar is shown indefinitely.
<img src="https://user-images.githubusercontent.com/5469652/134484103-9c52d930-0884-4f01-824a-d8305f5f8703.png" width=200 />

**Versions**
- Software Version: 1.0(17) and 1.0(6)
- OS: iOS 14.7.1
- Browser: Brave
- Mobile device: iPhone 11 Pro

**Comment by concordium-cl** [comment]
Will move to jira.
