### ISSUE TITLE
Testnet GTU drop amount is incorrect

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-reference-wallet-ios#62]
**Bug Description**

The app assumes that the testnet GTU drop amount is 100GTU, but it has been updated in the wallet proxy to 2000GTU.

**Steps to Reproduce**
Create an account on testnet. Open the balance.

**Expected Result**
The testnet drop button should show 2000GTU, and the pending drop transaction should also show as 2000GTU.

**Actual Result**
They show as 100GTU, until the transaction is confirmed (at which point it corrects to 2000GTU).

**Versions**
- Software Version: 1.0.16
- OS: iOS

**Comment by concordium-cl** [comment]
Change to 2000 for now. Android task to be created.

**Comment by jens-concordium** [comment]
This is verified and working in 1.0(19).
