### ISSUE TITLE
Update text shown in failed identity issuance dialog and e-mail

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#65]
**Description**
The text shown in the dialog when identity issuance fails in the mobile wallet should be updated a bit.

When an e-mail client is found, the text should now mention that Concordium is also added to CC. If an e-mail client is not found, it should be added that Concordium can optionally be added to CC. Additionally, when an e-client is not found, the manual copy function, should copy the full text that would have automatically entered in the e-mail.

The text added to the automatically generated e-mails should also be updated to include a bit more info, like app version and which OS the app is running. iOS / Android should be enough, but if possible the specific OS version would be nice as well.

The change can be seen in Figma in flow 21. The semi transparent pages does not have any changes.

**Comment by jens-concordium** [comment]
@concordium-cl @kristiyandobrev 

This is almost updated as intended in 1.0(19). I've found two small things:

1. The app version shown in the auto-filled e-mail does not include build number, so it just says 1.0 - Do you know if it's possible to include build number as well, @kristiyandobrev? It is shown in the "About" tab on the "More" page, so I guess it's available somewhere.

2. When no e-mail client is available, the "Copy reference" option on the dialog still only copies the reference. It should copy the full text, that is now autofilled in the e-mail, when a client is available. I'm sorry if this wasn't clear from the issue text above, and I've also tried to make it a bit clearer in the Figma flow.
