### ISSUE TITLE
Information in memo-raw files is wrongly interpreted

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#66]
**_Related to task https://github.com/Concordium/concordium-reference-wallet-ios/issues/34_**

**Bug Description**
For a memo.txt with content _this is a memo text in a file_ some characters are wrongly interpreted as type and length.

Below is the file and the old network dashboard output.
![memo file](https://user-images.githubusercontent.com/69570978/135465102-31bd0129-7630-4262-b5bd-f003181860fe.JPG)

The iOS output is exactly the same:
![IMG_4013](https://user-images.githubusercontent.com/69570978/135465491-533edcc6-b510-4cb3-a56b-333d55808c76.jpg)

@abizjak explanation: _The letter t's ASCII code is 116 which is 01110100 in binary. The way CBOR encoding works is it looks at the first 3 bits to determine the type, in this case the type is determined to be (3=011 ) which is string. The remaining 5 bits are 10100 which is 20 in decimal, which is interpreted as the lenght of the remaining string. Hence the remaining 20 bytes are decoded._

**Steps to Reproduce**
- do a scheduled transfer with `--memo-raw memo.txt`

**Expected Result**
The memo should be printed as hex value in case of invalid CBOR.

**Actual Result**
See above.

**Versions**
- 1.0.18
- iOS 14.7
- iPhone 11

**Comment by abizjak** [comment]
So basically this is related to what I was asking here https://github.com/Concordium/concordium-reference-wallet-ios/pull/57#discussion_r716933271 The decoder must ensure that the entire input was decoded, not just that the prefix was.

**Comment by kristiyandobrev** [comment]
@abizjak 

How does a similar transaction looks on web and/or Android ?
