### ISSUE TITLE
Indication missing when adding a new receiver via QR code to address book without camera access permission

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#72]
**Bug Description**
When adding a new receiver to the address book via the QR code functionality, you will get a black screen without any indication of what is wrong, if the app does not have camera access permissions.

Issue should be fixed similarly to https://github.com/Concordium/concordium-reference-wallet-ios/issues/24 with indicating the cause and guiding the user to the settings.

**Steps to Reproduce**
- make sure the Concordium app does not have camera access permission
- go to address book
- add new receiver via QR code functionality

**Expected Result**
The user is told that the app needs camera access and is guided to the settings.

**Actual Result**
Black screen that does not scan the QR code.

**Versions**
- iOS 14.7
- iPhone 11
- Concordium app 1.0.18

**Comment by mh-concordium** [comment]
I was able to reproduce this issue by following the description.
- Disable camera permissions
- Start application
- Try to scan address

**Versions**
- Software Version: 3.0.0 (40)
- OS:14.8.1
- Browser
- Mobile device: iPhone SE

**Comment by mh-concordium** [comment]
Issue was fixed but not on all pages where capability is provided.

If user selects:
More -> Address Book -> + QRCodeButton

Issue is persisted in there.

Wallet version: 3.0.0 (42)
iOS: 15.4.1
Device: iPhone SE

**Comment by ZB-concordium** [comment]
Verified.
Wallet version: 3.0.0 (44)
iOS: 15.5
Device: iPhone SE
