### ISSUE TITLE
Automatic synchronization between two phones does not include decryption key

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#78]
**Bug Description**
The user created an account on his old phone, and afterwards he used a new phone and automatically synchronized the data to the new phone. It's unclear if backup and restore from iCloud or the Quick Start functionality to sync two phones directly was used. Now the user cannot send GTU or shield GTU from the account on his new phone. It seems the app cannot decrypt its own keys on the new phone. 

![ios_error](https://user-images.githubusercontent.com/69570978/138657967-eb12aed4-7997-45fb-af14-a0ed1d5d6ec5.png)

**Expected Result**
Synchronization via iCloud & Quick Start includes all keys.

**Actual Result**
Synchronization does not backup all keys.

**Versions**
- Concordium Wallet 1.0.4
- iOS

**Comment by concordium-cl** [comment]
From discussion with Mjølner:
- backup is encrypted
- app data & key is protected by app passcode encryption

Note: It should be added to documentation (new backup info page) that passcode is needed for restoring on new phone.

**Comment by jens-concordium** [comment]
@concordium-cl - How did we decide to proceed with this? I can't really test it.

**Comment by concordium-cl** [comment]
@jens-concordium - I suggest to leave it as is. We cannot really test it and it is not our official recommendation but just the last straw.

**Comment by jens-concordium** [comment]
@concordium-cl Ah, yeah that was it. I guess we can just remove the issue from the board, as we can't technically verify it?

**Comment by kristiyandobrev** [comment]
Not sure if I mentioned it earlier but the way to verify is unfortunately only on a production build 😶
