### ISSUE TITLE
Notification on succesful new account

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#79]
**Description**
Currently when an account is finalized, the user is not given any explicit notification. People have been asking for more explicit notifications, and while we cannot push notifications to the OS at the moment, we could show one inside the app after polling the wallet proxy.

This notification could also be used to suggest that people should make a backup after a new account has been added, just to encourage backups more often. 

So the suggested change would be:
- Show a pop-up when an account has finalized, that also reminds the user to make a backup. The backup then has two buttons that say "Okay" and "Make backup". Okay will just close the pop-up and leave the user on the current page, and Make backup would take them to the export flow.

Sketches showing the change, can be found in Figma.

**Versions**
- Software Version: 1.0(20)
- OS: iOS

**Comment by jens-concordium** [comment]
@kristiyandobrev @concordium-cl 

Single new initial and regular accounts seem to give the notification as intended, but I can't get the "batched" notification to appear. Instead it seems to give an error about not being able to connect to the server. Here's a recording showing the scenario:

https://user-images.githubusercontent.com/76045015/141071255-77382a9a-3790-406a-90a7-96e588ea0a6e.mov

**Comment by concordium-cl** [comment]
To be tested additionally: Import a wallet with finalized accounts. Observe that there is no "new account "notification dialog shown.

**Comment by concordium-cl** [comment]
Tested single and multi[le account creation and import scenario.

Fixed in 1.0.23.
