### ISSUE TITLE
New UI for account cards

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#86]
**Task description**
As an attempt to improve the UX of the mobile wallet, the central "account cards" will be redesigned. The main difference is the removal of the shielded balance from the account accards, in favor of adding three buttons to the design instead: SEND, RECEIVE and MORE.

- Pressing SEND will start the flow of a simple transfer.
- Pressing RECEIVE will take the user to the "Address" page of the account, the one with the QR code and share options.
- Pressing MORE will take the user to the specific account page, the one that shows the transaction log.

The new design can be found in "Flow 0" here: https://www.figma.com/file/pUlYPsHRU0Hvm0NoGIvxrv/Mobile-Wallet?node-id=2881%3A13697

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: Testnet 2.0
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE
