### ISSUE TITLE
Force update functionality

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#89]
**Task description**
[placeholder]

**Sub-tasks**
- [ ] subtask 1
- [ ] subtask 2
- [ ] subtask 3

*Add label for component and priority.*

**Comment by XOOPsoft** [comment]
Request:
GET /v0/appSettings?platform=android&appVersion=84
platform can be either android or ios.
appVersion is an integer.

Response json example:
{ "status":"ok", "url":"app-store-link" }

status can be:
"ok"
"warning"
"needsUpdate"

ok means that the app will not present anything to the user. The app can be used as normal.
warning means that the user will see a popup with a message like "There is a new version of the app. Do you want to update now?" Answer options are: "Update now", "Later".
needsUpdate means that the user will see a popup saying "There is a new version of the app. Please update now."
Answer option is only one "OK". The user cannot continue to use the app.

url is for example:
"https://play.google.com/store/apps/details?id=software.concordium.mobilewallet.mainnet"
"https://apps.apple.com/dk/app/concordium-mobile-wallet/id1566996491"
url can also point to a completely new app if that is required.

**Comment by Bargsteen** [comment]
Everything worked as expected 👍
