### ISSUE TITLE
Show terms and conditions again after update, if the T&C has changed

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#99]
**Task description**

At the moment the user is not shown the T&C after an update to the app, that also updated the T&C. 

Each time the T&C has been updated, the user should be shown the new one upon opening the app. However, we might have to let the user make an export, so they don't get locked out if they for some reason don't agree with the new T&C.

**Comment by jens-concordium** [comment]
@concordium-cl, this looks good to me on iOS 15 in v1.0(25)

**Comment by concordium-cl** [comment]
Verified also on iOS 14.7.1, iPhone11, v1.0.25.
